### ISSUE TITLE
How do you use non-local variables in react?

### ISSUE THREAD

**Issue by mectors** [divkit/divkit#18]
The documentation [https://divkit.tech/en/doc/overview/concepts/variables.html] explains how to use non-local variables in Android but not in React or Web in general. Given that the id field is not used in the HTML, it is not possible to just grab an element and listen for clicks for instance. Ideally you could do this. It would also be great if state could be changed by other parts of the web page which are in another Divkit or not even Divkit, e.g. a React component. 

Many thanks for a great open source product. I tried for weeks to get Adaptive Cards working consistently and couldn't. Where DivKit was easy and just works.

**Comment by 4eb0da** [comment]
Hello!
Global variables in web could be used in the same way as Android:
https://github.com/divkit/divkit/tree/main/client/web/divkit#variables
(there is a mistake in the package import)
There is no such example for React, but it should be the same
I hope it helps)
