### ISSUE TITLE
Can't build android client: Could not install Gradle  from app artifactory.yandex.net 

### ISSUE THREAD

**Issue by Cher80** [divkit/divkit#2]
looks like artifactory.yandex.net  is not reachable:
Could not install Gradle distribution from 'https://artifactory.yandex.net/artifactory/gradle-distributions/distributions/gradle-7.4.1-all.zip'.

**Comment by SynteZZZ** [comment]
Teething problems, we're working on a fix

**Comment by rucas152** [comment]
so changes the repository it's just a gradle (https://services.gradle.org/distributions/)

**Comment by gulevsky** [comment]
[This commit](https://github.com/divkit/divkit/commit/272512621a64a1a81e77c809f5018f3f5f61bfe3) should fix build configuration. You can try to execute `./gradlew :divkit-demo-app:installDebug` to check out the problem is solved.
