### ISSUE TITLE
Support jsx syntax for typescript on server side

### ISSUE THREAD

**Issue by maximelkin** [divkit/divkit#21]
This could be done with custom jsxTransform
https://babeljs.io/docs/babel-plugin-transform-react-jsx
or 
https://www.typescriptlang.org/tsconfig#jsxFactory

I can implements this, but honestly not really good with docs

**Comment by 4eb0da** [comment]
Right now we have no plans to add such functionality, but we can answer you about the current structure of the project.
We accept contributions)
As part of the functionality, you will need to generate jsx types, and this will require changes in the api generator
