### ISSUE TITLE
Unknown type of action (url=div-action://download?url=

### ISSUE THREAD

**Issue by hulygun** [divkit/divkit#29]
The instruction (https://divkit.tech/en/doc/overview/concepts/interaction.html#loading-data) say use div-action://download but json-builder and web playground don`t know this action type. How to use Loading more data?

**Comment by 4eb0da** [comment]
Hello!
What you mean saying "json-builder don't know this action type"?
What language are you talking about? In typescript, for example, url is a plain string, it should work as expected
About web playground. [Right now](https://github.com/divkit/divkit/blob/main/schema/div-patch.json#L4) this type of action is not supported by the web DivKit, but it will be supported in a several weeks

**Comment by hulygun** [comment]
Thank you! In the Python json-builder, the validator does not allow the object to be built.

`class MainScreen(dk.DivContainer):
    __template_name__ = 'main'

    id = "main"
    height = dk.DivMatchParentSize()
    background = [dk.DivImageBackground(image_url='http://192.168.1.55:8000/static/main_bg.jpeg')]
    visibility_action = dk.DivVisibilityAction(
        url='div-action://download?url=example.url'
    )`
Result:
` visibility_action = dk.DivVisibilityAction(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pydivkit/core/entities.py", line 305, in __init__
    setattr(self, field_name, field.default)
  File ".../pydivkit/core/entities.py", line 617, in __setattr__
    super().__setattr__(key, value)
  File ".../pydivkit/core/entities.py", line 341, in __setattr__
    value = _cast_value_type(value, field_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pydivkit/core/entities.py", line 103, in _cast_value_type
    raise ValueError(
ValueError: Value None has wrong type. Expected type is typing.Union[pydivkit.core.fields.Expr, str].`
