### ISSUE TITLE
How i can launch site locally?

### ISSUE THREAD

**Issue by shalom-aviv** [divkit/divkit#38]
Hello,

I am not a web developer, and I'm unsure how to run the project located in the following folder: [site](https://github.com/divkit/divkit/tree/main/site).

I would appreciate any assistance or guidance.

Thank you.

**Comment by 4eb0da** [comment]
Hello
Right now, the site configuration contains some deployment-related data, and these configs are omitted
There is also a new section "visual editor", which is provided only as an implementation
Without both of them, it's impossible to just run it
The source code of the site can be used as an example of a project with DivKit itself, including markup rendering, schema integration, server code and developer tools
The source code of the site can be made available to run without external dependencies and configurations, but this requires some work, and this work has not been done yet, sorry(
