### ISSUE TITLE
DivPercentageSize bug? (python)

### ISSUE THREAD

**Issue by v-krupsky** [divkit/divkit#40]
Hi!

Could you please help to check if this is a bug?

This code in python:
`mydiv = dk.DivContainer(
    ...
    width = dk.DivPercentageSize(value=100),
    ...
)`

produces the following error:
`ValueError: Value <pydivkit.div.div_percentage_size.DivPercentageSize object at 0x102d79e90> has wrong type. Expected type is typing.Union[pydivkit.div.div_fixed_size.DivFixedSize, pydivkit.div.div_match_parent_size.DivMatchParentSize, pydivkit.div.div_wrap_content_size.DivWrapContentSize, NoneType].`

I'm trying to have a 100% width for an element.

BR, Ivan

**Comment by v-krupsky** [comment]
I have a suspicion that adding
`    {
      "$ref": "div-percentage-size.json",
      "$description": "translations.json#/div_percentage_size"
    }`
to `schema/div-size.json` would solve this but would like to hear your thoughts on this.

**Comment by lunarstill** [comment]
No, it is not a bug. `DivPercentageSize` has nothing to do with element width. Use `DivMatchParentSize` if you want element to have 100% width of its parent.
