### ISSUE TITLE
Gradle could not resolve all task dependencies

### ISSUE THREAD

**Issue by AndreiKud** [divkit/divkit#44]
Hello! Tried to build **divkit-demo-app** for android.
```
Could not find com.yandex:pulse:2.2.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/yandex/pulse/2.2.4/pulse-2.2.4.pom
       - https://repo.maven.apache.org/maven2/com/yandex/pulse/2.2.4/pulse-2.2.4.pom
     Required by:
         project :divkit-perftests
```

Commenting out `implementation "com.yandex:pulse:$versions.pulse"` seems to not cause any problems.

**Comment by divkit** [comment]
Ooops, thanx, will fix it!

**Comment by vyaivanove** [comment]
Thank you for reporting on this problem, it should be resolved at this point.
https://github.com/divkit/divkit/commit/4853a71a2c7605c56f139276eb3d841e8e7b9123

I'm closing the issue, please reopen it if the issue persists.
