### ISSUE TITLE
Issue on Android - Horizontal list doesn't scroll when it's in HorizontalPager

### ISSUE THREAD

**Issue by xiaoqian0408** [divkit/divkit#48]
Hi,
I'm integrating the divkit sdk into our android app project.
In my template, there's a horizontal list, and it's supposed to be scrollable. Usually it works well, but when the Div2View is put inside a page of a HorizontalPager, the horizontal list was no longer scrollable, which is not the expected behavior. Can you take a look? Thanks

I'm able to reproduce it with the sample project attached.
[Sample.zip](https://github.com/user-attachments/files/15920456/Sample.zip)

**Comment by divkit** [comment]
Hello!
Apparently, the parent container intercepts the scrolls. You need to redefine the taches in it and pass them to the child views

**Comment by xiaoqian0408** [comment]
But the child view is Div2View, how to pass redefined taches to it? Is there a sample I can refer to?

**Comment by Tayrinn** [comment]
You could add DivExtension and override onInterceptTouchEvent in this. Take a look in div-pinch-to-zoom-extension

**Comment by xiaoqian0408** [comment]
@Tayrinn got it, thanks, I've just tried with an extension, it works.
