### ISSUE TITLE
divkit website down?

### ISSUE THREAD

**Issue by kasperkamperman** [divkit/divkit#7]
For two days I get when trying to visit your website. I tried using several VPN's. No issue with other websites/services. 

This site can’t be reacheddivkit.tech’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_STARTED

**Comment by insane-developer** [comment]
Hello kasperkamperman!
It seems that it's something [on your side](https://downforeveryoneorjustme.com/divkit.tech).
Could you please execute the following command in Command Prompt/Power Shell (if you have Windows) or in your console (if you have Mac or Linux):
`nslookup divkit.tech`
Normally it would output something like this:
```$ nslookup divkit.tech
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	divkit.tech
Address: 87.250.254.64
Name:	divkit.tech
Address: 2a02:6b8::4b4
```
If you get something different (namely, different addresses or no address at all), you should probably look into your DNS settings.

**Comment by kasperkamperman** [comment]
I managed to visit it now, however I get a different output when I do an nslookup:

```
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	divkit.tech
Address: 87.250.254.64
```
